#!/bin/sh

set -e

path="$HOME/.determinal"

if [ -e $path/.git ]; then
  cd $path && git pull
else
  git clone https://github.com/filippo-liverani/determinal.git $path
fi

brew install wget
brew cask install iterm2

wget -N -P ~/Library/Fonts https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Inconsolata/complete/Inconsolata%20Nerd%20Font%20Complete.otf?raw=true

cp -f $path/com.googlecode.iterm2.plist "$HOME/Library/Preferences/com.googlecode.iterm2.plist"
